apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "13000"
      port: 13000
      targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
