apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (HEAD)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
    - name: "18443"
      port: 18443
      targetPort: 8443
    - name: "18080"
      port: 18080
      targetPort: 8080
    - name: "19990"
      port: 19990
      targetPort: 9990
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
