version: '2'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:2
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

  # sleeps for a second on startup to allow the configure container to run first.
  teleport:
    image: quay.io/gravitational/teleport-lab:${TELEPORT_VERSION}
    container_name: teleport
    entrypoint: /bin/sh
    hostname: luna.teleport
    command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport.d/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    networks:
      teleport:
        aliases:
          - proxy.luna.teleport

  # The bootstrap container generates certificates and then immediately exits.
  bootstrap:
    image: quay.io/gravitational/teleport-lab:${TELEPORT_VERSION}
    container_name: teleport-bootstrap
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/generate-certs.sh"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    depends_on:
      - teleport
    networks:
      - teleport

  #
  # openssh is a demo of openssh node
  #
  openssh:
    image: quay.io/gravitational/teleport-lab:${TELEPORT_VERSION}
    container_name: openssh
    hostname: mars.openssh.teleport
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/start-sshd.sh"
    mem_limit: 300m
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap
    networks:
      teleport:
        aliases:
          - mars.openssh.teleport

  #
  # term is a container with a terminal to try things out
  #
  term:
    image: quay.io/gravitational/teleport-lab:${TELEPORT_VERSION}
    hostname: term
    container_name: term
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    mem_limit: 300m
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap
    networks:
      - teleport

volumes:
  certs:
  data:
  config:

networks:
  teleport:
  jenkins_data:
    driver: local